#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          7
bspc config normal_border_color #db0087
bspc config active_border_color "#db0087"
bspc config focused_border_color "#db0087"
bspc config presel_border_color "#db0087"
bspc config top_padding 10
bspc config bottom_padding 30
bspc config right_padding -7
bspc config left_padding -7

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc rule -a Pavucontrol state=floating 
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a steam state=floating
#picom & # not using picom because felt like minimalistic bspwm better fits the aesthic. It's not riced so idk, feel free to turn on and customize.
# also... picom breaks stuff...

sxhkd &
# POLYBAR - ACTIVATION!!!!
~/.config/polybar/launch.sh
feh --bg-scale ~/.config/bspwm/black.png
xfsettingsd &
xsetroot -cursor_name left_ptr




